# Generated by Django 3.1.5 on 2021-01-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_employee_user'),
        ('schedule_app', '0002_chat'),
    ]

    operations = [
    ]
