# Generated by Django 3.1.5 on 2021-01-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_position_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], max_length=200, null=True),
        ),
    ]
