# Generated by Django 3.1.5 on 2021-01-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0003_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Important', 'Not Important'), ('Important', 'Important'), ('Very Important', 'Very Important')], max_length=200, null=True),
        ),
    ]
