# Generated by Django 3.1.5 on 2021-01-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0006_auto_20210120_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='permissions',
        ),
    ]
