# Generated by Django 3.1.5 on 2021-01-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0009_auto_20210120_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='position',
        ),
    ]
