# Generated by Django 3.1.5 on 2021-01-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0010_remove_task_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
    ]
