# Generated by Django 3.1.5 on 2021-01-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0014_auto_20210121_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='note',
        ),
    ]
