# Generated by Django 3.1.5 on 2021-01-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0014_auto_20210121_1719'),
        ('schedule_app', '0012_auto_20210121_1137'),
    ]

    operations = [
    ]
