# Generated by Django 3.1.5 on 2021-01-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0015_merge_20210122_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='note',
        ),
    ]
