# Generated by Django 3.1.5 on 2021-01-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0017_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
