# Generated by Django 3.1.5 on 2021-01-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0022_auto_20210125_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
